FROM php:7.4-fpm
# FROM php:8.0-fpm

COPY ./php.ini /etc/php/conf.d/php.ini
RUN chmod 644 /etc/php/conf.d/php.ini

COPY --from=composer:2.0 /usr/bin/composer /usr/bin/composer

RUN apt-get update && \
    apt-get -y install unzip

RUN docker-php-ext-install pdo_mysql

# # laravel-echo
# RUN apt-get install -y zip git
# RUN git clone https://github.com/phpredis/phpredis.git /usr/src/php/ext/redis
# RUN docker-php-ext-install redis

WORKDIR /var/www/